In [2]:
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
path = '/content/drive/MyDrive/Datasets/imdb_data.csv'
imdb_df = pd.read_csv(path)

In [ ]:
imdb_df.head()
#To get all the columns in the data frame we write a code in python
pd.set_option('display.max_columns', None)

#Before writing this code we were able to see three dots in between the columns section and all the column names
# were not visble to us. with this code we are able to access all the columns

In [ ]:
#Apply Function
# This function is used in pandas data frame to apply a user defined function to a pandas data frame
#for example we want to change the name of one coo lumn to upper case how will we do it?
#efficient method is using a function upper to do it at once
#lets see how we do it here

In [ ]:
#lets define a function
def upper_case(column_name):
  return column_name.upper()

In [ ]:
#after defining a function we make a new column in which we display the upper case charachters
imdb_df['Capital_column'] # lets name the column as capital_column
imdb_df['Capital_column'] = imdb_df['title'] #we want to apply the changes in this title column
imdb_df['Capital_column'] = imdb_df['title'].apply(upper_case)  #here to apply the function to the column we use apply function in pandas

In [ ]:
imdb_df['Capital_column'] = imdb_df['title'].apply(upper_case)

In [ ]:
#now lets display these both title and capital
imdb_df[['title','Capital_column']].head() #then to acess it we need to put double square brackets

,title,Capital_column
0,Hot Tub Time Machine 2,HOT TUB TIME MACHINE 2
1,The Princess Diaries 2: Royal Engagement,THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT
2,Whiplash,WHIPLASH
3,Kahaani,KAHAANI
4,Marine Boy,MARINE BOY

In [ ]:
import numpy as np

In [ ]:
def revised_profit(revenue, budget):
  if revenue > 0:
    new_profit = revenue - budget
  else:
    new_profit = np.nan

  return new_profit

In [ ]:
imdb_df['new_profit']= imdb_df.apply(lambda x:revised_profit(x['revenue'],x['budget']),axis = 1)
imdb_df[['revenue','budget','new_profit']].head()

    revenue    budget  new_profit
0  12314651  14000000    -1685349
1  95149435  40000000    55149435
2  13092000   3300000     9792000
3  16000000   1200000    14800000
4   3923970         0     3923970

In [ ]:
list(imdb_df.columns)

['id',
 'belongs_to_collection',
 'budget',
 'genres',
 'homepage',
 'imdb_id',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'poster_path',
 'production_companies',
 'production_countries',
 'release_date',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'Keywords',
 'cast',
 'crew',
 'revenue',
 'new_profit']

In [ ]:
path = '/content/drive/MyDrive/Datasets/imdb_data.csv'
imdb_df = pd.read_csv(path)
imdb_df['Profit_'] = imdb_df['revenue'] - imdb_df['budget']
imdb_df['profit_margin'] = imdb_df.apply(lambda x: (x['Profit_'] / x['revenue']) * 100, axis=1)
imdb_df['is_profitting'] = imdb_df.apply(lambda x: True if x['profit_margin'] >0 else False, axis = 1)
imdb_df[['profit_margin','is_profitting']].head()

   profit_margin  is_profitting
0     -13.685723          False
1      57.960864           True
2      74.793767           True
3      92.500000           True
4     100.000000           True

In [5]:
imdb1 = imdb_df[imdb_df['runtime'] >= 150]
imdb2 = imdb_df[ (imdb_df['runtime'] < 150) & (imdb_df['runtime'] > 100 )]
imdb3 = imdb_df[imdb_df['runtime'] <= 100]

In [11]:
pd.concat([imdb1,imdb2,imdb3])

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
47,48,NaN,44000000,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",http://thehatefuleight.com/,tt3460252,en,The Hateful Eight,Bounty hunters seek shelter from a raging bliz...,20.328822,...,12/25/15,167.0,"[{'iso_639_1': 'es', 'name': 'Español'}, {'iso...",Released,No one comes up here without a damn good reason.,The Hateful Eight,"[{'id': 801, 'name': 'bounty hunter'}, {'id': ...","[{'cast_id': 22, 'character': 'Major Marquis W...","[{'credit_id': '538aa95ec3a368714e0005b3', 'de...",155760117
51,52,NaN,12000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 35, '...",NaN,tt0059243,en,The Great Race,"Professional daredevil and white-suited hero, ...",4.473327,...,7/1/65,160.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"The movie with 20,000-mile or one-million-laug...",The Great Race,"[{'id': 9253, 'name': 'slapstick'}, {'id': 159...","[{'cast_id': 1, 'character': 'Prof. Fate', 'cr...","[{'credit_id': '52fe445e9251416c75032581', 'de...",25333333
76,77,NaN,500000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt0242572,ta,Kandukondain Kandukondain,Two young women with differing views on love f...,0.660663,...,5/5/00,157.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kandukondain Kandukondain,NaN,"[{'cast_id': 1, 'character': 'Manohar', 'credi...","[{'credit_id': '52fe47c7c3a368484e0d8f41', 'de...",500000
97,98,NaN,0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",NaN,tt1772980,ru,Mishen,"In the year 2020, a group of wealthy Moscovite...",1.042112,...,6/26/11,158.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,NaN,Target,NaN,"[{'cast_id': 1001, 'character': 'Victor', 'cre...","[{'credit_id': '58cdbad4c3a36850e9011085', 'de...",73000
107,108,NaN,72000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,tt0112573,en,Braveheart,"Enraged at the slaughter of Murron, his new br...",20.755149,...,5/24/95,177.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Every man dies. Not every man truly lives.,Braveheart,"[{'id': 30, 'name': 'individual'}, {'id': 388,...","[{'cast_id': 5, 'character': 'William Wallace'...","[{'credit_id': '52fe4225c3a36847f80079c1', 'de...",210000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2987,2988,NaN,0,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...",NaN,tt0096246,en,The Terror Within,Experiments in biological warfare have destroy...,1.292125,...,1/20/89,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It Wants To Get Out!,The Terror Within,"[{'id': 1299, 'name': 'monster'}, {'id': 1852,...","[{'cast_id': 4, 'character': 'Hal', 'credit_id...","[{'credit_id': '52fe45d9c3a368484e072511', 'de...",858591
2988,2989,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0301978,fa,ده,A visual social examination in the form of ten...,0.984515,...,5/20/02,94.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,NaN,Ten,"[{'id': 1156, 'name': 'sister sister relations...","[{'cast_id': 2, 'character': 'Driver', 'credit...","[{'credit_id': '52fe460a9251416c7506b0a7', 'de...",105656
2989,2990,NaN,0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",NaN,tt0206367,en,The Trumpet Of The Swan,The adventures of a young Trumpeter swan who c...,0.851599,...,5/11/01,75.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Sometimes being different helps you to find yo...,The Trumpet Of The Swan,"[{'id': 6653, 'name': 'trumpet'}, {'id': 10407...","[{'cast_id': 1, 'character': 'Father', 'credit...","[{'credit_id': '58bc9d609251416084044b0e', 'de...",100202
2990,2991,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0118663,en,B.A.P.S.,Can two clueless Georgia homegirls with big he...,1.560980,...,3/28/97,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,These Pretty Women... Are Clueless!,B.A.P.S.,"[{'id': 1437, 'name': 'burglar'}, {'id': 1946,...","[{'cast_id': 3, 'character': 'Nisi', 'credit_i...","[{'credit_id': '52fe477b9251416c7509af57', 'de...",7240837
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386

In [13]:
imdb1.shape

(135, 23)

In [14]:
imdb2.shape

(1586, 23)

In [16]:
sample_df = pd.concat([imdb1,imdb2],axis = 1)

In [17]:
pd.set_option('display.max_columns', None)

In [19]:
sample_df.head(1)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
47,48.0,NaN,44000000.0,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",http://thehatefuleight.com/,tt3460252,en,The Hateful Eight,Bounty hunters seek shelter from a raging bliz...,20.328822,/fqe8JxDNO8B8QfOGTdjh6sPCdSC.jpg,"[{'name': 'Double Feature Films', 'id': 215}, ...","[{'iso_3166_1': 'US', 'name': 'United States o...",12/25/15,167.0,"[{'iso_639_1': 'es', 'name': 'Español'}, {'iso...",Released,No one comes up here without a damn good reason.,The Hateful Eight,"[{'id': 801, 'name': 'bounty hunter'}, {'id': ...","[{'cast_id': 22, 'character': 'Major Marquis W...","[{'credit_id': '538aa95ec3a368714e0005b3', 'de...",155760117.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
#only english movies
imdb_df[imdb_df['original_language'] == 'en'].head(1)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,/tQtWuwvMf0hCc2QR2tkolwl7c3c.jpg,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651

In [34]:
released_films = imdb_df.loc[imdb_df['status'] == 'Released',['title']]
released_films.head()

                                      title
0                    Hot Tub Time Machine 2
1  The Princess Diaries 2: Royal Engagement
2                                  Whiplash
3                                   Kahaani
4                                Marine Boy

In [35]:
long_movies = imdb_df.loc[imdb_df['runtime'] >= 100,['imdb_id','original_language']]

english_movies = imdb_df[imdb_df['original_language'] == 'en']

In [63]:
#inner join
new_table = pd.merge(english_movies[['imdb_id','runtime']],long_movies,how = 'outer', left_on='imdb_id',right_on='imdb_id')

In [65]:
new_table.head()

     imdb_id  runtime original_language
0  tt2637294     93.0               NaN
1  tt0368933    113.0                en
2  tt2582802    105.0                en
3  tt0093743     83.0               NaN
4  tt0431021     92.0               NaN

In [53]:
long_movies.shape

(1820, 2)